### ISSUE TITLE
Error in executing caffe_ftr.py

### ISSUE THREAD

**Issue by darrenlei** [AlfredXiangWu/face_verification_experiment#70]
Dear wu:
  我用caffe_ftr.py抽取特征时，
python caffe_ftr.py ../../proto/LightenedCNN_A_deploy.prototxt ../../model/LightenedCNN_A.caffemodel ~/work/data/3624302/ ~/work/data/test_face_list.txt eltwise6 leifan.mat

Traceback (most recent call last):
  File "caffe_ftr.py", line 494, in <module>
    main(sys.argv[1:])
  File "caffe_ftr.py", line 411, in main
    extract_features_to_mat(argv[0], argv[1], None, argv[2], argv[3], argv[4], argv[5])
  File "caffe_ftr.py", line 201, in extract_features_to_mat
    img_list, data_mean, layer_name, image_as_grey)
  File "caffe_ftr.py", line 113, in extract_feature
    net.set_phase_test()
AttributeError: 'Classifier' object has no attribute 'set_phase_test'

---

python caffe_ftr.py ../../proto/LightenedCNN_B_deploy.prototxt ../../model/LightenedCNN_B.caffemodel ~/work/data/3624302/ ~/work/data/test_face_list.txt eltwise6 leifan.mat

F1020 16:04:13.743952 12389 insert_splits.cpp:29] Unknown bottom blob 'label' (layer 'accuracy', bottom index 1)
**\* Check failure stack trace: ***
Aborted (core dumped)

Wu 老师， 这是什么原因，我什么都没有改，难道是caffe 版本不对， 期待您的解答。

**Comment by AlfredXiangWu** [comment]
caffe_ftr.py对应caffe-rc版，现在最新的caffe版本python接口改了没法用

**Comment by darrenlei** [comment]
dear wu, 我用了一个更新的caffe_ftr.py， 但是在抽取某些层的特征时，出现KeyError 比如：
python caffe_ftr_new.py ../../proto/LightenedCNN_A_deploy.prototxt ../../model/LightenedCNN_A.caffemodel ~/work/data/3624302/ ~/work/data/test_face_list.txt etlwise4 leifan.mat

Traceback (most recent call last):
  File "caffe_ftr_new.py", line 1003, in <module>
    main(sys.argv[1:])
  File "caffe_ftr_new.py", line 837, in main
    extract_features_to_mat(argv[0], argv[1], None, argv[2], argv[3], argv[4], argv[5], True)
  File "caffe_ftr_new.py", line 417, in extract_features_to_mat
    img_list, data_mean, layer_name, image_as_grey)
  File "caffe_ftr_new.py", line 269, in extract_feature
    shp = blobs[layer_name].shape
KeyError: 'etlwise4'

Traceback (most recent call last):
  File "caffe_ftr_new.py", line 1003, in <module>
    main(sys.argv[1:])
  File "caffe_ftr_new.py", line 837, in main
    extract_features_to_mat(argv[0], argv[1], None, argv[2], argv[3], argv[4], argv[5], True)
  File "caffe_ftr_new.py", line 417, in extract_features_to_mat
    img_list, data_mean, layer_name, image_as_grey)
  File "caffe_ftr_new.py", line 269, in extract_feature
    shp = blobs[layer_name].shape
KeyError: 'slice_fc1'

好像是找不到哪些层，名字出错了。
我是不是最好还是用你说的caffe_ftr.py对应caffe-rc版
